# /etc/stunnel/stunnel.conf

client = yes
setuid = stunnel
setgid = stunnel

[bitcoin-rpc]
accept = 127.0.0.1:18332
connect = bitcoin-rpc.eniemela.fi:8335

# TLS verification
verifyChain = yes
CAfile = /etc/ssl/certs/ca-certificates.crt
checkHost = bitcoin-rpc.eniemela.fi
sni = bitcoin-rpc.eniemela.fi

sslVersionMin = TLSv1.2
